### PR TITLE
generate unique names

### PR DESCRIPTION
**Pull request by Mrigank11**
First of all, thanks for this great project! We use it a lot to share files (assignments :p) in the lab.
There's just one issue: it gets very difficult to find the receipt when multiple users have snapdrop open ( Similar to #69).

This PR aims to fix this issue by generating names using the `unique-names-generator` library.

### CODE REVIEW

**Comment by bluenevus** [comment]
Please merge...much needed feature here too

**Comment by bmcgonag** [comment]
So, is there active acceptance of pull requests?  If not, perhaps this project needs to be forked so someone else can continue it.  I like the things I see, and the options foldks are giving in the issues list, but not seeing activity from the owner.

**Comment by Mhowser** [comment]
is there any progress on this?

**Comment by PaulSzymanski** [comment]
Thanks for your contribution! I changed the layout for the name to be more prominent so it is not overlooked. Also, I changed the dictionary to adjective + animal

**Comment by RobinLinus** [comment]
We published a new version giving each device a random name. How do you guys like it?

Special thanks to @Mrigank11 for implementing this!

**Pull request merged**
