### PR TITLE
Resolves #202

### LINKED ISSUE #202: Make textarea autogrowing
The title says it all, it would be great if the newly introduced multi line text input for sending texts was a little higher or ideally grows with the entered text...

### PR DESCRIPTION
**Pull request by MontelAle**
### Problem Description

As stated in Issue #202 the textarea in the chat (dialog) window does not auto-expand. 

The height of the textarea is statically set. This is makes writing messages longer than a few words quite inconvenient. At the moment a sidebar appears to allow scrolling of longer messages.

### Root Cause

The problem is inherent to the use of the `textarea` HTML tag, which doesn't allow automatic "expansion".

### Solution Description

The desired Behaviour (an auto-expanding textarea) can be achieved by using a contenteditable div. This is exactly what this change does. 

The `textarea` HTML tag is substituted by a "contenteditable" `div`. This `div `shares all of the properties (style and HTML attributes) of the current `textarea` tag. The new `div` shares the functionalities of the current tag as well (ui.js has been edited to mirror current behaviour).

The "contenteditable" `div` allows for the desired behaviour. It now auto-expands following text input until it reaches a `max-height` of 300px. After that a sidebar appears, to allow further input.

### Testing

I have not managed to test this new feature extensively. It should be supported on almost every browser (except for Opera Mini).

Still, further testing is needed.

### CODE REVIEW

**Comment by abhijit-hota** [comment]
Sweet. Although it will be very good if you can fix some of the redundant whitespace changes.

**Comment by MontelAle** [comment]
I'm sorry, I have only now noticed the many only whitespace diffs. 

I have tried to fix the problem through git, but I am not very comfortable with it. Therefore I haven't managed to fix it (without creating a whole another PR).

I think that the easiest solution may be merging using the `-Xignore-all-space` option.

**Comment by abhijit-hota** [comment]
@MontelAle Oh that's ok. Collaborators can look into before merging and decide what's best. 

P.S. 

> I think that the easiest solution may be merging using the `-Xignore-all-space` option.

I wasn't aware of such an option. Thanks =)

**Review by shawttx1969 — APPROVED** [review]

**Comment by RobinLinus** [comment]
Thanks a lot! Great work!!

**Pull request merged**
