### PR TITLE
Dark Mode Supported

### PR DESCRIPTION
**Pull request by fasih**
Using macOS dark mode with always open tab `https://snapdrop.net` I feel like let's make this PWA, dark mode supported.

Thanks to @RobinLinus for creating and hosting this amazing app.

### CODE REVIEW

**Comment by fasih** [comment]
Resolved conflicts & merged from latest master @RobinLinus

**Comment by RobinLinus** [comment]
Thanks a lot for your work! I really appreciate it. Though, I am not sure if I will merge this PR. Main reasons are:
- Is there much gain for many users? 
- It is a significant amount of code.
- It introduces costs because we have to maintain almost two designs now.

@all if you want this PR to be merged, keep voting with a like on @fasih's post at the top.

**Comment by abhijit-hota** [comment]
@fasih It would be really great if you can post a screenshot of the dark mode here!

**Comment by fasih** [comment]
> @fasih It would be really great if you can post a screenshot of the dark mode here!

Sure @abhijit-hota I am attaching screenshots as well

Screenshot 2020-12-20 at 9 24 17 AM
Screenshot 2020-12-20 at 9 23 55 AM
Screenshot 2020-12-20 at 9 23 05 AM
Screenshot 2020-12-20 at 9 22 52 AM
Screenshot 2020-12-20 at 9 22 17 AM
Screenshot 2020-12-20 at 9 21 45 AM

**Review by Bellisario — APPROVED** [review]

**Pull request merged**
