### PR TITLE
feat: created chrome extension

### PR DESCRIPTION
**Pull request by Aarush-Goyal**
## Fixes Issue #314 

image

- I have wrapped the website as a iframe but we cannot send a file using the extension because chrome kills the popup when the file manager opens up due to focus shift.

- The functionality of recieving files is working perfectly though, and there is no problem in sending or recieving

### CODE REVIEW

**Comment by Aarush-Goyal** [comment]
### How to add the extension for testing

**Go to chrome://extensions**

image

- Click on load and unpacked and then select the extension folder

**Comment by RobinLinus** [comment]
This PR changes 17 files. Looks like something is wrong here?

**Comment by Aarush-Goyal** [comment]
@RobinLinus I accidently forgot to remove the unused images that's why changed 17 files
Sorry  :sweat_smile: !

**Comment by fm-sys** [comment]
IMHO such an extention should be developed in a dedicated repo.

**Comment by ueen** [comment]
Hey, i already did a WebExtension with several options to solve the problem of sending files, have a look
https://github.com/ueen/SnapdropFirefoxAddon

@RobinLinus 
Maybe you can merge (some version) of this PR https://github.com/RobinLinus/snapdrop/pull/278 that adds related projects to the README so they're easier to find and duplicate work is prevented :)

**Pull request closed without merging**
