### PR TITLE
Add wake-lock

### LINKED ISSUE #412: Implement wake lock?
[Like this comment already suggested](https://github.com/RobinLinus/snapdrop/issues/109#issuecomment-613000556), it would be a great idea to add wake lock to avoid a smartphone go out due to inactivity.

I can implement this feature and propose a PR, is this okay @RobinLinus ?

### PR DESCRIPTION
**Pull request by Myzel394**
closes #412

### CODE REVIEW

**Review by Bellisario — CHANGES_REQUESTED** [review]
Very good work, but I think `nosleep.min.js` file should be added to the service worker, so the browser doesn't need to fetch it every time Snapdrop loads.

**Comment by Myzel394** [comment]
Afaik the service worker is in a different thread than the webpage. So if we would add it, it would stop the service worker's thread from going to sleep and not the webpage's one. But I'm not sure, correct me if I'm wrong.

**Comment by Bellisario** [comment]
> Afaik the service worker is in a different thread than the webpage. So if we would add it, it would stop the service worker's thread from going to sleep and not the webpage's one. But I'm not sure, correct me if I'm wrong.

Sorry because of my bad explain.
I intended that the service worker, actually, is caching about all resources of the page (like all scripts, see code below) after the first load (and, so, service work install), in this way, when you load Snapdrop, it loads from a local saved (and cached) resource that permits a faster page load.
I just was suggesting to add also this resource, too, so, the user can experience a faster Snapdrop.

P.S.: to explain me more, let me saying this... I didn't intended to add the script into the service worker but just add it's file entry, as other files below. I don't know if I'm explaining...

https://github.com/RobinLinus/snapdrop/blob/bd3d13d48a754121b53aa91034579466937ff2e3/client/service-worker.js#L1-L12

**Review by Bellisario — APPROVED** [review]
Good job @Myzel394, now it's perfect!

@RobinLinus, could you approve these changes? Thanks!

**Comment by Myzel394** [comment]
@RobinLinus Could you take a look at this PR please?

**Comment by schlagmichdoch** [comment]
Have you tested your code? It does not work for me. The Documentation reads:
>   This function call must be wrapped in a user input event handler e.g. a mouse or touch handler

I guess you would have to call it on click / touch events. That would mean, only the sending part could successfully enable this with the current implementation. I plan to change this with #560

**Comment by Myzel394** [comment]
@schlagmichdoch If I remember correctly it worked for me on Android using Firefox, Brave and Chrome

**Comment by schlagmichdoch** [comment]
@Myzel394 I tested on iOS only, but nice that it works on Android!
After putting it in a click handler it is now working on iOS as well 🦾

**Comment by schlagmichdoch** [comment]
This is implemented on https://pairdrop.net
File Transfers need to be accepted by the receiving peer so we have a click handler for the sending and the receiving peer.
Take a look at this commit: https://github.com/schlagmichdoch/PairDrop/commit/168d10a898dbe0fa2c1061ec36f7092282f44122

**Pull request closed without merging**
