### PR TITLE
improvement in recieved text messages

### PR DESCRIPTION
**Pull request by navece**

### CODE REVIEW

**Comment by RobinLinus** [comment]
What is the purpose for this PR? The multiline issue was fixed in 6a5ad0f1fbe930b6953ba8b5f96a0e5964158c78, no?

**Comment by navece** [comment]
sorry for that i am a noob for github

**Comment by RobinLinus** [comment]
no problemo :) Thanks for your support!

**Comment by navece** [comment]
Screenshot from 2020-12-30 01-14-08
Screenshot from 2020-12-30 01-14-18

**Comment by navece** [comment]
see the difference in both images
some text were invisible before

**Comment by RobinLinus** [comment]
Indeed this is a different issue than 6a5ad0f. I just pushed a slightly different fix. This ensures text like `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` gets wrapped correctly , and as well texts like
`a
      a
      a
 a     
`

**Comment by navece** [comment]
see the word company
Screenshot from 2020-12-30 02-06-18

**Pull request closed without merging**
